version: '2'

services:
  proxy:
    image: zaidhusseini/fullstack-flapjacks:proxy.v1.0.0
    #build: .
    container_name: 'proxy_server'
    depends_on:
      - 'postgresDB'
      - 'database'
      - 'reservations'
      - 'suggested'
      - 'about'
      - 'menu'
    ports: 
      - '3000:3000'

  reservations:
    image: zaidhusseini/fullstack-flapjacks:reservations.v1.0.0
    #build: ./reservation-service
    container_name: 'reservations'
    depends_on:
      - 'database'
    ports: 
      - '2003:2003'

  suggested:
    image: zaidhusseini/fullstack-flapjacks:suggested.v1.0.0
    container_name: 'suggested'
    depends_on:
      - 'database'
    ports: 
      - '6001:6001'

  about:
    image: zaidhusseini/fullstack-flapjacks:about.v1.0.0
    container_name: 'about'
    depends_on:
      - 'database'
    ports:
      - '1128:1128'

  menu:
    image: zaidhusseini/fullstack-flapjacks:menu.v1.0.0
    container_name: 'menu'
    depends_on:
      - 'postgresDB'
    ports:
      - '6600:6600'

  seed:
    image: zaidhusseini/fullstack-flapjacks:seed.v1.0.0
    container_name: 'seed-mongodb'
    depends_on:
      - 'database'

  seed2:
    image: zaidhusseini/fullstack-flapjacks:seed2.v1.0.0
    container_name: 'seed-pg'
    depends_on:
      - 'postgresDB'

  database:
    image: mongo:3.6.2

  postgresDB:
    image: postgres:10.2
    environment:
      POSTGRES_DB: menus
